displayName=Maiden Nylo Freeze Chance
author=Yrself
description=Shows freeze chance for Nylocas Matomenos in the Theatre of Blood
tags=tob,theatre of blood,maiden,freeze,nylo
plugins=com.nylofreeze.NyloFreezePlugin